### ISSUE TITLE
When disconnected, minimongo insert is pushing data to view but not send to server when reconnecting.

### ISSUE THREAD

**Issue by radiegtya** [inProgress-team/react-native-meteor#29]
When disconnected, minimongo insert is pushing data to view but not send to server when reconnecting.

example:

ddp is connected and trigger this method (this is working just fine)
```javascript
Meteor.collection('somecol').insert(data);
```

when disconnected and call this method (data is pushed to view/listView correctly while offline)
```javascript
Meteor.collection('somecol').insert(data);
```

but when ddp reconnecting the real collection is not inserted to server. (Meteor default behaviour allowing offline saved data to be inserted to real server when reconnecting)

How do you think about this? @Mokto . Thanks 

(Btw sorry for interrupting you everyday lol)

**Comment by Mokto** [comment]
You are absolutely right @radiegtya !!

It is fine you interrupt me, you make this plugin better and better by reporting issues ! ;)

**Comment by radiegtya** [comment]
ok will wait for this one working :+1:

**Comment by Mokto** [comment]
Fixed in 1.0.0-beta15.

**Comment by radiegtya** [comment]
Cool, will try it asap

**Comment by radiegtya** [comment]
Still not working @Mokto. When reconnecting my offline data disappeared. I am using react-native-meteor-beta18

**Comment by radiegtya** [comment]
Sorry, can you test it @Mokto . And if it's still not working on latest version, would you mind to reopen it?

**Comment by Mokto** [comment]
I also confirm this works in 1.0.0-beta19.

**Comment by radiegtya** [comment]
I'll test it

**Comment by Mokto** [comment]
Closing issue for now then.

**Comment by radiegtya** [comment]
Coll! This is working. THanks @Mokto
